from __future__ import annotations

import json
from pathlib import Path

import typer

from .analyzer import summarize_architecture, summarize_attack_surface
from .defensive_review import render_defensive_review
from .analyzers import (
    analyze_repository,
    get_available_modules,
    get_available_repository_modules,
    get_analyzer_metadata,
    install_analyzer_module,
    resolve_run_analyzers,
    select_requested_analyzers,
)
from .cve import query_vulnerabilities
from .diff import (
    FindingSnapshot,
    diff_findings,
    load_baseline,
    render_diff_markdown,
)
from .graph import build_graph
from .llm_review import LlmReviewError, generate_llm_review
from .progress import create_progress
from .recon_to_analysis import translate_recon
from .report import render_console_summary, render_pr_comment, write_reports
from .suggest import detect_ecosystems
from .suppress import apply_suppressions, collect_suppressions

app = typer.Typer(help="AttackMap: understand your system and map your attack surface.")

# Prepended to vulnerability-hypotheses.md (#80) so the framing is unmissable
# even if a reader skips straight to the file: these are leads, not detections.
HUNT_BANNER = (
    "> ⚠️ **These are HYPOTHESES to confirm, not confirmed vulnerabilities.**\n"
    "> Generated by an LLM reasoning over AttackMap's static evidence as a red-team\n"
    "> analyst. Each hypothesis cites the evidence it rests on and lists what a human\n"
    "> must verify. Treat every item as a lead requiring code review before action —\n"
    "> no CVE assignment, no exploitation instructions.\n\n"
)

# Prepended to remediation.md (#106): suggestions are review-first, not
# auto-applied.
REMEDIATION_BANNER = (
    "> 🛠️ **Suggested fixes to review, not auto-applied.**\n"
    "> LLM-proposed remediations grounded in AttackMap's static evidence. Each is\n"
    "> the smallest change to remove a weakness class; review the diff, confirm the\n"
    "> intent (e.g. whether a route should require auth), and run the verification\n"
    "> step before applying. No exploit code.\n\n"
)


@app.command()
def analyze(
    path: str = typer.Argument(".", help="Path to the repository to analyze."),
    output: str = typer.Option("reports", "--output", "-o", help="Directory for generated reports."),
    format: str = typer.Option("all", "--format", help="Output format: all, markdown, or json."),
    module: list[str] | None = typer.Option(
        None,
        "--module",
        "-m",
        help="Analyzer module(s) to run. Repeat to select multiple. Missing external analyzers are auto-installed from the mlaify GitHub organization.",
    ),
    llm: bool = typer.Option(
        False,
        "--llm",
        help="Generate a narrative defensive review by calling Claude with the evidence pack. Auth resolves automatically: ANTHROPIC_API_KEY → ANTHROPIC_AUTH_TOKEN → `claude` CLI (subscription auth). Force a backend with --llm-backend.",
    ),
    llm_provider: str = typer.Option(
        "claude",
        "--llm-provider",
        help="LLM provider for --llm/--hunt/--remediate: 'claude' (default, Anthropic) or 'openai' (OpenAI/Codex).",
    ),
    llm_model: str | None = typer.Option(
        None,
        "--llm-model",
        help="Model ID for --llm. Claude provider: e.g. claude-opus-4-8 (default), claude-fable-5, claude-sonnet-5, claude-opus-4-7. OpenAI provider: e.g. gpt-5-codex (default), gpt-5.5, gpt-5.4, gpt-5.4-mini — any model ID is passed through verbatim.",
    ),
    llm_effort: str | None = typer.Option(
        None,
        "--llm-effort",
        help="Effort for --llm: low|medium|high|xhigh|max. Defaults to high. For OpenAI, xhigh/max clamp to high (Responses API reasoning effort tops out at high).",
    ),
    llm_backend: str = typer.Option(
        "auto",
        "--llm-backend",
        help="Which backend --llm uses. Claude: 'auto' tries ANTHROPIC_API_KEY → ANTHROPIC_AUTH_TOKEN → `claude` CLI; 'api' forces the SDK; 'cli' forces the `claude` CLI. OpenAI: 'auto' tries OPENAI_API_KEY then the `codex` CLI; 'api' forces the OpenAI SDK; 'cli' forces `codex exec` (your `codex login` subscription).",
    ),
    llm_speed: str = typer.Option(
        "standard",
        "--llm-speed",
        help="LLM output speed: 'standard' (default) or 'fast'. Fast mode (~2.5x output speed, premium price) applies only to Opus 4.8/4.7 via the API backend; other models/backends fall back to standard.",
    ),
    hunt: bool = typer.Option(
        False,
        "--hunt",
        help="Vulnerability-hypothesis mode (#80): have Claude reason over the full evidence pack as a red-team analyst and propose ranked, human-verifiable exploit-chain HYPOTHESES (leads, not detections) to vulnerability-hypotheses.md. Uses the same LLM auth/backend as --llm.",
    ),
    verify: bool = typer.Option(
        False,
        "--verify",
        help="With --hunt: adjudicate each hypothesis against the actual source at cited locations — CONFIRMED / REFUTED / NEEDS HUMAN REVIEW (#hunt-verify). AttackMap feeds the code excerpts to the model.",
    ),
    remediate: bool = typer.Option(
        False,
        "--remediate",
        help="Remediation mode (#106): have Claude propose concrete, review-first fixes per finding (suggested diffs / precise instructions, grounded in evidence) to remediation.md. Uses the same LLM auth/backend as --llm.",
    ),
    baseline: str | None = typer.Option(
        None,
        "--baseline",
        help="Path to a prior `attackmap-report.json`. When set, emit a diff (new/persisted/resolved) alongside the fresh report.",
    ),
    diff_output: str | None = typer.Option(
        None,
        "--diff-output",
        help="Path to write the Markdown diff. Defaults to <output>/attackmap-diff.md when --baseline is set.",
    ),
    fail_on_new_high: bool = typer.Option(
        False,
        "--fail-on-new-high",
        help="Exit non-zero if the diff introduces any new HIGH-severity findings. Requires --baseline.",
    ),
    cve: bool = typer.Option(
        False,
        "--cve",
        help="Cross-reference SBOM entries against OSV.dev and surface vulnerable dependencies as findings. Cached under ~/.attackmap/cache/osv/ (24h TTL). Off by default because it does network I/O.",
    ),
    no_progress: bool = typer.Option(
        False,
        "--no-progress",
        help="Disable the live progress bar / ETA during scanning. Progress auto-disables when stderr isn't a terminal (CI, piped output).",
    ),
    progress_format: str = typer.Option(
        "auto",
        "--progress-format",
        help="Progress reporting: 'auto' (TTY bar when stderr is a terminal), 'json' (newline-delimited JSON events on stderr, for GUI/tool front-ends), or 'none'. --no-progress is equivalent to 'none'.",
    ),
    pr_comment: str | None = typer.Option(
        None,
        "--pr-comment",
        help="Write a Markdown PR summary comment to this path (for the GitHub Action / bot to post). Includes the baseline diff and top exploitability when available.",
    ),
    no_suppress: bool = typer.Option(
        False,
        "--no-suppress",
        help="Ignore all suppressions — the .attackmap-suppress.yaml baseline and inline `attackmap:ignore` directives (#144). Use for a full, unfiltered audit.",
    ),
    suppress_file: str | None = typer.Option(
        None,
        "--suppress-file",
        help="Path to a suppression baseline, overriding auto-discovery of .attackmap-suppress.yaml at the repo root (#144).",
    ),
) -> None:
    repo_path = Path(path).resolve()
    if not repo_path.exists():
        raise typer.BadParameter(f"Path does not exist: {repo_path}")
    # Validate diff-mode flag combinations before doing any real work.
    if fail_on_new_high and baseline is None:
        raise typer.BadParameter("--fail-on-new-high requires --baseline to be set.")
    if baseline is not None:
        baseline_path = Path(baseline)
        if not baseline_path.exists():
            raise typer.BadParameter(f"Baseline report not found: {baseline_path}")

    selected_analyzers = None
    if module:
        try:
            selected_analyzers = select_requested_analyzers(module, auto_install=True)
        except ValueError as exc:
            raise typer.BadParameter(str(exc)) from exc

    if progress_format not in {"auto", "tty", "json", "none"}:
        raise typer.BadParameter("--progress-format must be one of: auto, json, none.")
    if llm_speed not in {"standard", "fast"}:
        raise typer.BadParameter("--llm-speed must be one of: standard, fast.")
    if llm_provider not in {"claude", "openai"}:
        raise typer.BadParameter("--llm-provider must be one of: claude, openai.")
    # Provider-aware label for the "via X" progress/echo strings.
    llm_display = "Codex" if llm_provider == "openai" else "Claude"
    if llm_provider == "openai" and llm_speed == "fast" and (llm or hunt or remediate):
        typer.echo(
            "Note: --llm-speed fast is Claude-only; ignoring it for the OpenAI provider.",
            err=True,
        )
    active_analyzers = resolve_run_analyzers(repo_path, analyzers=selected_analyzers)
    scan_progress = create_progress(progress_format, no_progress=no_progress)
    scan = analyze_repository(repo_path, analyzers=active_analyzers, progress=scan_progress)
    if cve and scan.dependencies:
        typer.echo(f"Checking {len(scan.dependencies)} dependencies against OSV.dev…")
        scan_progress.stage(f"Checking {len(scan.dependencies)} dependencies against OSV.dev")
        try:
            vulns, cve_summary = query_vulnerabilities(scan.dependencies)
        finally:
            scan_progress.done()
        scan.vulnerabilities = vulns
        typer.echo(
            f"CVE lookup: {len(vulns)} vulnerabilit"
            f"{'y' if len(vulns) == 1 else 'ies'} across "
            f"{cve_summary.queried} query(s), {cve_summary.cached} cache hit(s), "
            f"{cve_summary.skipped_no_version} skipped (no queryable version), "
            f"{cve_summary.network_errors} network error(s)."
        )
    graph = build_graph(scan)
    analysis = translate_recon(scan)
    attack_surfaces = analysis.attack_surfaces
    architecture_md = summarize_architecture(scan, graph)
    attack_surface_md = summarize_attack_surface(scan, attack_surfaces)
    findings = analysis.findings
    attack_paths = analysis.attack_paths

    # Finding suppression (#144): the .attackmap-suppress.yaml baseline plus
    # inline `attackmap:ignore` directives. Suppressed findings are partitioned
    # out of the active set used for the review, console, and the diff gate —
    # but retained (with reasons) in report.json and marked suppressed in SARIF.
    suppressed_findings: list = []
    if no_suppress:
        if suppress_file is not None:
            typer.echo("Note: --suppress-file is ignored because --no-suppress is set.", err=True)
    else:
        explicit = Path(suppress_file) if suppress_file else None
        if explicit is not None and not explicit.exists():
            raise typer.BadParameter(f"Suppress file not found: {explicit}")
        suppset, sup_warnings = collect_suppressions(repo_path, findings, explicit_file=explicit)
        for warning in sup_warnings:
            typer.echo(f"Suppression warning: {warning}", err=True)
        outcome = apply_suppressions(findings, suppset)
        findings = outcome.active
        suppressed_findings = outcome.suppressed
        if suppressed_findings:
            typer.echo("")
            typer.echo(f"Suppressed {len(suppressed_findings)} finding(s) (#144):")
            for summary_line in outcome.summary_lines():
                typer.echo(summary_line)

    defensive_review_md = render_defensive_review(scan, attack_surfaces, findings, attack_paths)

    write_reports(
        output,
        scan,
        architecture_md,
        attack_surface_md,
        defensive_review_md,
        attack_surfaces,
        findings,
        attack_paths,
        analyzer_metadata=[
            {
                "name": metadata.name,
                "description": metadata.description,
                "scope": metadata.scope,
                "ecosystems": list(metadata.ecosystems),
            }
            for metadata in (get_analyzer_metadata(analyzer) for analyzer in active_analyzers)
        ],
        suppressed=suppressed_findings,
    )
    typer.echo(render_console_summary(scan, findings, attack_paths))
    typer.echo("")
    typer.echo(f"Reports written to: {Path(output).resolve()}")

    diff_exit_code = 0
    diff = None
    if baseline is not None:
        baseline_path = Path(baseline)
        try:
            baseline_snapshots = load_baseline(baseline_path)
        except (OSError, ValueError) as exc:
            raise typer.BadParameter(f"Failed to read baseline: {exc}") from exc
        current_snapshots = [FindingSnapshot.from_finding(f) for f in findings]
        diff = diff_findings(baseline_snapshots, current_snapshots)
        counts = diff.counts()
        typer.echo("")
        typer.echo(
            f"Diff vs baseline: {counts['new']} new, "
            f"{counts['persisted']} persisted, {counts['resolved']} resolved."
        )
        diff_path = Path(diff_output) if diff_output else Path(output) / "attackmap-diff.md"
        diff_path.parent.mkdir(parents=True, exist_ok=True)
        diff_path.write_text(render_diff_markdown(diff), encoding="utf-8")
        typer.echo(f"Diff written to: {diff_path.resolve()}")
        if fail_on_new_high and diff.has_new_high:
            new_high_titles = [s.title for s in diff.new if s.severity == "high"]
            typer.echo("", err=True)
            typer.echo(
                "New HIGH findings introduced (failing per --fail-on-new-high):",
                err=True,
            )
            for t in new_high_titles:
                typer.echo(f"  - {t}", err=True)
            diff_exit_code = 1

    if pr_comment is not None:
        pr_path = Path(pr_comment)
        pr_path.parent.mkdir(parents=True, exist_ok=True)
        pr_path.write_text(render_pr_comment(findings, diff), encoding="utf-8")
        typer.echo(f"PR comment written to: {pr_path.resolve()}")

    if llm:
        try:
            effort_value = None
            if llm_effort is not None:
                if llm_effort not in {"low", "medium", "high", "xhigh", "max"}:
                    raise typer.BadParameter(
                        f"Invalid --llm-effort '{llm_effort}'. Use one of: low, medium, high, xhigh, max."
                    )
                effort_value = llm_effort  # type: ignore[assignment]

            if llm_backend not in {"auto", "api", "cli"}:
                raise typer.BadParameter(
                    f"Invalid --llm-backend '{llm_backend}'. Use one of: auto, api, cli."
                )

            typer.echo("")
            typer.echo(
                f"Generating narrative review via {llm_display} (backend={llm_backend}, may take a minute)..."
            )
            scan_progress.stage(
                f"{llm_display} is writing the defensive review (backend={llm_backend})"
            )
            try:
                result = generate_llm_review(
                    scan,
                    attack_surfaces,
                    findings,
                    attack_paths,
                    model=llm_model,
                    effort=effort_value,  # type: ignore[arg-type]
                    backend=llm_backend,  # type: ignore[arg-type]
                    speed=llm_speed,  # type: ignore[arg-type]
                    provider=llm_provider,  # type: ignore[arg-type]
                )
            finally:
                scan_progress.done()
        except LlmReviewError as exc:
            typer.echo(f"LLM review skipped: {exc}", err=True)
        else:
            output_path = Path(output)
            llm_md_path = output_path / "defensive-review-llm.md"
            llm_md_path.write_text(result.markdown + "\n", encoding="utf-8")
            llm_meta_path = output_path / "defensive-review-llm.meta.json"
            llm_meta_path.write_text(
                json.dumps(
                    {
                        "backend": result.backend,
                        "model": result.model,
                        "stop_reason": result.stop_reason,
                        "usage": result.usage,
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            typer.echo(f"LLM review written to: {llm_md_path.resolve()} (backend={result.backend})")

    if hunt:
        try:
            hunt_effort_value = None
            if llm_effort is not None:
                if llm_effort not in {"low", "medium", "high", "xhigh", "max"}:
                    raise typer.BadParameter(
                        f"Invalid --llm-effort '{llm_effort}'. Use one of: low, medium, high, xhigh, max."
                    )
                hunt_effort_value = llm_effort  # type: ignore[assignment]
            if llm_backend not in {"auto", "api", "cli"}:
                raise typer.BadParameter(
                    f"Invalid --llm-backend '{llm_backend}'. Use one of: auto, api, cli."
                )
            typer.echo("")
            hunt_mode = "hunt_verify" if verify else "hunt"
            typer.echo(
                f"Hunting for vulnerability hypotheses via {llm_display} "
                f"({'adjudicated against source, ' if verify else ''}backend={llm_backend}, may take a minute)..."
            )
            scan_progress.stage(
                f"{llm_display} is hunting exploit-chain hypotheses"
                f"{' + verifying against source' if verify else ''} (backend={llm_backend})"
            )
            try:
                hunt_result = generate_llm_review(
                    scan,
                    attack_surfaces,
                    findings,
                    attack_paths,
                    model=llm_model,
                    effort=hunt_effort_value,  # type: ignore[arg-type]
                    backend=llm_backend,  # type: ignore[arg-type]
                    mode=hunt_mode,  # type: ignore[arg-type]
                    speed=llm_speed,  # type: ignore[arg-type]
                    provider=llm_provider,  # type: ignore[arg-type]
                )
            finally:
                scan_progress.done()
        except LlmReviewError as exc:
            typer.echo(f"Vulnerability hunt skipped: {exc}", err=True)
        else:
            output_path = Path(output)
            hunt_md_path = output_path / "vulnerability-hypotheses.md"
            hunt_md_path.write_text(HUNT_BANNER + hunt_result.markdown + "\n", encoding="utf-8")
            hunt_meta_path = output_path / "vulnerability-hypotheses.meta.json"
            hunt_meta_path.write_text(
                json.dumps(
                    {
                        "backend": hunt_result.backend,
                        "model": hunt_result.model,
                        "stop_reason": hunt_result.stop_reason,
                        "usage": hunt_result.usage,
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            typer.echo(
                f"Vulnerability hypotheses written to: {hunt_md_path.resolve()} "
                f"(backend={hunt_result.backend})"
            )

    if remediate:
        try:
            rem_effort_value = None
            if llm_effort is not None:
                if llm_effort not in {"low", "medium", "high", "xhigh", "max"}:
                    raise typer.BadParameter(
                        f"Invalid --llm-effort '{llm_effort}'. Use one of: low, medium, high, xhigh, max."
                    )
                rem_effort_value = llm_effort  # type: ignore[assignment]
            if llm_backend not in {"auto", "api", "cli"}:
                raise typer.BadParameter(
                    f"Invalid --llm-backend '{llm_backend}'. Use one of: auto, api, cli."
                )
            typer.echo("")
            typer.echo(
                f"Generating remediation suggestions via {llm_display} (backend={llm_backend}, may take a minute)..."
            )
            scan_progress.stage(
                f"{llm_display} is drafting remediation suggestions (backend={llm_backend})"
            )
            try:
                rem_result = generate_llm_review(
                    scan,
                    attack_surfaces,
                    findings,
                    attack_paths,
                    model=llm_model,
                    effort=rem_effort_value,  # type: ignore[arg-type]
                    backend=llm_backend,  # type: ignore[arg-type]
                    mode="remediate",
                    speed=llm_speed,  # type: ignore[arg-type]
                    provider=llm_provider,  # type: ignore[arg-type]
                )
            finally:
                scan_progress.done()
        except LlmReviewError as exc:
            typer.echo(f"Remediation skipped: {exc}", err=True)
        else:
            output_path = Path(output)
            rem_md_path = output_path / "remediation.md"
            rem_md_path.write_text(REMEDIATION_BANNER + rem_result.markdown + "\n", encoding="utf-8")
            rem_meta_path = output_path / "remediation.meta.json"
            rem_meta_path.write_text(
                json.dumps(
                    {
                        "backend": rem_result.backend,
                        "model": rem_result.model,
                        "stop_reason": rem_result.stop_reason,
                        "usage": rem_result.usage,
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            typer.echo(
                f"Remediation suggestions written to: {rem_md_path.resolve()} "
                f"(backend={rem_result.backend})"
            )

    if diff_exit_code:
        raise typer.Exit(code=diff_exit_code)


@app.command("modules")
def modules(
    json_output: bool = typer.Option(
        False,
        "--json",
        help="Emit the installed analyzer modules as a JSON array "
        "(name/display_name/description/scope/ecosystems/enabled_by_default). "
        "Network-free — the remote module-repository section is omitted. "
        "Intended for tool / GUI front-ends that offer analyzer selection.",
    ),
) -> None:
    available_modules = get_available_modules()
    if json_output:
        payload = [
            {
                "name": meta.name,
                "display_name": meta.display_name or meta.name,
                "description": meta.description,
                "scope": meta.scope,
                "ecosystems": list(meta.ecosystems),
                "enabled_by_default": meta.enabled_by_default,
            }
            for meta in available_modules
        ]
        typer.echo(json.dumps(payload, indent=2))
        return

    if not available_modules:
        typer.echo("No analyzer modules are currently available.")
    else:
        typer.echo("Available analyzer modules (installed):")
        for module_metadata in available_modules:
            ecosystems = ", ".join(module_metadata.ecosystems) if module_metadata.ecosystems else "none"
            typer.echo(f"- {module_metadata.name}: {module_metadata.description}")
            typer.echo(f"  scope: {module_metadata.scope}")
            typer.echo(f"  ecosystems: {ecosystems}")

    typer.echo("")
    typer.echo("Available module repositories (mlaify GitHub org):")
    try:
        repository_modules = get_available_repository_modules()
    except ValueError as exc:
        typer.echo(f"- Unable to fetch remote module repositories: {exc}")
        return

    if not repository_modules:
        typer.echo("- No module repositories were discovered.")
        return

    for module in repository_modules:
        typer.echo(f"- {module.analyzer_name} ({module.repo_name})")
        typer.echo(f"  repo: {module.web_url}")


@app.command("suggest")
def suggest(
    path: str = typer.Argument(".", help="Path to the repository to inspect."),
    install: bool = typer.Option(
        False,
        "--install",
        help="After printing, offer to `pip install` the missing recommended plugins.",
    ),
    yes: bool = typer.Option(
        False,
        "--yes",
        "-y",
        help="Skip the confirmation prompt when used with --install.",
    ),
    show_installed: bool = typer.Option(
        False,
        "--show-installed",
        help="Include already-installed plugins in the output (marked accordingly).",
    ),
) -> None:
    """Recommend analyzer plugins for the shape of the given repository."""
    repo = Path(path).resolve()
    if not repo.exists() or not repo.is_dir():
        typer.echo(f"Path does not exist or is not a directory: {repo}")
        raise typer.Exit(code=1)

    suggestions = detect_ecosystems(repo)
    missing = [s for s in suggestions if not s.installed]
    installed = [s for s in suggestions if s.installed]

    if not suggestions:
        typer.echo(f"No AttackMap plugins matched the shape of {repo}.")
        raise typer.Exit(code=0)

    shown = suggestions if show_installed else missing
    if not shown:
        typer.echo("All recommended plugins are already installed:")
        for s in installed:
            typer.echo(f"  - {s.plugin} (installed)")
        raise typer.Exit(code=0)

    typer.echo(f"Recommended plugins for {repo}:")
    for s in shown:
        tag = " (installed)" if s.installed else ""
        typer.echo(f"  - {s.plugin}{tag}")
        typer.echo(f"      matches: {', '.join(s.matched_signals)}")
        if not s.installed:
            typer.echo(f"      install: {s.pip_install}")

    if not install:
        return
    if not missing:
        typer.echo("Nothing to install — all recommended plugins are already present.")
        return

    typer.echo("")
    typer.echo("The following plugins will be installed via pip:")
    for s in missing:
        typer.echo(f"  - {s.plugin}")
    if not yes and not typer.confirm("Proceed?", default=False):
        typer.echo("Aborted.")
        raise typer.Exit(code=1)

    for s in missing:
        typer.echo(f"Installing {s.plugin}…")
        try:
            install_analyzer_module(s.plugin)
        except Exception as exc:  # noqa: BLE001 — surface pip failures verbatim
            typer.echo(f"  Failed: {exc}")
            raise typer.Exit(code=1) from exc
    typer.echo("Done.")


if __name__ == "__main__":
    app()
