"""Official analyzer plugins, pinned to immutable commits (#237).

Generated by scripts/update_plugin_lock.py — do not edit by hand. Only
these may be auto-installed by `-m` / `suggest --install`, and only at
the pinned commit.
"""

OFFICIAL_PLUGINS: list[dict] = [
    {
        'repo': 'attackmap-analyzer-python',
        'package': 'attackmap-analyzer-python',
        'version': '0.1.0',
        'git_sha': '44ff509870de88512f37f080930dd2f2d4df3858',
        'entry_points': ['python'],
    },
    {
        'repo': 'attackmap-analyzer-rust',
        'package': 'attackmap-analyzer-rust',
        'version': '0.1.0',
        'git_sha': '884335b044d50677ee7ebc0b5d7bf1e6f79ca8d8',
        'entry_points': ['rust'],
    },
    {
        'repo': 'attackmap-analyzer-go',
        'package': 'attackmap-analyzer-go',
        'version': '0.1.0',
        'git_sha': '19e4d5981fb286ff8a6029a8f7f3b31e41ee3a34',
        'entry_points': ['go'],
    },
    {
        'repo': 'attackmap-analyzer-java-spring',
        'package': 'attackmap-analyzer-java-spring',
        'version': '0.1.0',
        'git_sha': '958010d1245988de530131b5596b5f9809420597',
        'entry_points': ['java_spring'],
    },
    {
        'repo': 'attackmap-analyzer-dotnet',
        'package': 'attackmap-analyzer-dotnet',
        'version': '0.1.0',
        'git_sha': '1196bbfe2cccde448f9da639c2ce5595c3dd5aba',
        'entry_points': ['dotnet'],
    },
    {
        'repo': 'attackmap-analyzer-terraform',
        'package': 'attackmap-analyzer-terraform',
        'version': '0.1.0',
        'git_sha': '6ea7d52e9fabb85ad0ef4b4dea31d5702c8cc677',
        'entry_points': ['terraform'],
    },
    {
        'repo': 'attackmap-analyzer-c',
        'package': 'attackmap-analyzer-c',
        'version': '0.1.0',
        'git_sha': 'bd1a1806b80f0f824befdd00bca992407e76a34b',
        'entry_points': ['c'],
    },
    {
        'repo': 'attackmap-analyzer-cpp',
        'package': 'attackmap-analyzer-cpp',
        'version': '0.1.0',
        'git_sha': '24388da39c95b562bb9bccbf483e20a162d7055f',
        'entry_points': ['cpp'],
    },
    {
        'repo': 'attackmap-analyzer-swift',
        'package': 'attackmap-analyzer-swift',
        'version': '0.1.0',
        'git_sha': '07344c54be7042a24145803729e6ae2548476f96',
        'entry_points': ['swift'],
    },
    {
        'repo': 'attackmap-analyzer-node-service',
        'package': 'attackmap-analyzer-node-service',
        'version': '0.2.0',
        'git_sha': '05638b5ac192bfd8249bd5199e2256171aafa32d',
        'entry_points': ['node_service'],
    },
    {
        'repo': 'attackmap-analyzer-atproto',
        'package': 'attackmap-analyzer-atproto',
        'version': '0.1.0',
        'git_sha': '5aeee5bb231cc2720bba384214da62e70af670cb',
        'entry_points': ['atproto'],
    },
    {
        'repo': 'attackmap-analyzer-php-web',
        'package': 'attackmap-analyzer-php-web',
        'version': '0.1.0',
        'git_sha': '732a7cb276b8e6503a0bfd064b1f9610924217e8',
        'entry_points': ['php_web'],
    },
    {
        'repo': 'attackmap-analyzer-php-laminas',
        'package': 'attackmap-analyzer-php-laminas',
        'version': '0.1.0',
        'git_sha': '0c53f2542d7878a09b5291949b3a3be404c3f6db',
        'entry_points': ['php_laminas'],
    },
    {
        'repo': 'attack-map-analyzer-omeka-s',
        'package': 'attackmap-analyzer-omeka-s',
        'version': '0.1.0',
        'git_sha': '9a7a820eea0ec1b6bd7680291f53aefa76256e13',
        'entry_points': ['omeka_s'],
    },
    {
        'repo': 'attackmap-analyzer-iac',
        'package': 'attackmap-analyzer-iac',
        'version': '0.1.0',
        'git_sha': '4b3d60aa349f37b67b83418ec0841675cf492fb9',
        'entry_points': ['iac'],
    },
]
