"""Official analyzer plugins, pinned to immutable commits (#237).

Generated by scripts/update_plugin_lock.py — do not edit by hand. Only
these may be auto-installed by `-m` / `suggest --install`, and only at
the pinned commit.
"""

OFFICIAL_PLUGINS: list[dict] = [
    {
        'repo': 'attackmap-analyzer-python',
        'package': 'attackmap-analyzer-python',
        'version': '0.1.0',
        'git_sha': '1bcce0dd5d639cb83ada65cc3f5024bb5a1d9782',
        'entry_points': ['python'],
    },
    {
        'repo': 'attackmap-analyzer-rust',
        'package': 'attackmap-analyzer-rust',
        'version': '0.1.0',
        'git_sha': 'c2e02d2855e6102153140f2644504b1cc0a95fb8',
        'entry_points': ['rust'],
    },
    {
        'repo': 'attackmap-analyzer-go',
        'package': 'attackmap-analyzer-go',
        'version': '0.1.0',
        'git_sha': '3fb5023704ba380cb5388cfea9e8753177b774e8',
        'entry_points': ['go'],
    },
    {
        'repo': 'attackmap-analyzer-java-spring',
        'package': 'attackmap-analyzer-java-spring',
        'version': '0.1.0',
        'git_sha': '1da4a81c1368e15371e8c285fe46ce964ab5c8fd',
        'entry_points': ['java_spring'],
    },
    {
        'repo': 'attackmap-analyzer-dotnet',
        'package': 'attackmap-analyzer-dotnet',
        'version': '0.1.0',
        'git_sha': '2c28e7342301ee2d193e670fd45b663e6781257a',
        'entry_points': ['dotnet'],
    },
    {
        'repo': 'attackmap-analyzer-terraform',
        'package': 'attackmap-analyzer-terraform',
        'version': '0.1.0',
        'git_sha': '8168393fbe430e8ff0273efd8c934a7cbaf88a3c',
        'entry_points': ['terraform'],
    },
    {
        'repo': 'attackmap-analyzer-c',
        'package': 'attackmap-analyzer-c',
        'version': '0.1.0',
        'git_sha': '4c2a6b3e48fbd044b85a6bcacd5845ed9464c125',
        'entry_points': ['c'],
    },
    {
        'repo': 'attackmap-analyzer-cpp',
        'package': 'attackmap-analyzer-cpp',
        'version': '0.1.0',
        'git_sha': '304d686630dd0d2a8afe66989e6ef9e84ecce8b1',
        'entry_points': ['cpp'],
    },
    {
        'repo': 'attackmap-analyzer-swift',
        'package': 'attackmap-analyzer-swift',
        'version': '0.1.0',
        'git_sha': 'bae13e58a49f46c15992197517cf9c036a75d83c',
        'entry_points': ['swift'],
    },
    {
        'repo': 'attackmap-analyzer-node-service',
        'package': 'attackmap-analyzer-node-service',
        'version': '0.2.0',
        'git_sha': '39ecbae65895e8cea546efa73eb7d031156dd4f8',
        'entry_points': ['node_service'],
    },
    {
        'repo': 'attackmap-analyzer-atproto',
        'package': 'attackmap-analyzer-atproto',
        'version': '0.1.0',
        'git_sha': '8bd04cdc8df6e0da02899473b681c50d47f5028a',
        'entry_points': ['atproto'],
    },
    {
        'repo': 'attackmap-analyzer-php-web',
        'package': 'attackmap-analyzer-php-web',
        'version': '0.1.0',
        'git_sha': 'd7329a58d16270bdefa2768f5e6deed6421e32f0',
        'entry_points': ['php_web'],
    },
    {
        'repo': 'attackmap-analyzer-php-laminas',
        'package': 'attackmap-analyzer-php-laminas',
        'version': '0.1.0',
        'git_sha': 'b7101504589f12d934e830237ada83bd0a66fbac',
        'entry_points': ['php_laminas'],
    },
    {
        'repo': 'attack-map-analyzer-omeka-s',
        'package': 'attackmap-analyzer-omeka-s',
        'version': '0.1.0',
        'git_sha': 'b4b7d3a2e58710860ecef0efdc8a56222557273d',
        'entry_points': ['omeka_s'],
    },
    {
        'repo': 'attackmap-analyzer-iac',
        'package': 'attackmap-analyzer-iac',
        'version': '0.1.0',
        'git_sha': '5a763ad5822a2309ba94da9b56d6392db65cbd6e',
        'entry_points': ['iac'],
    },
]
