"""Official analyzer plugins, pinned to immutable commits (#237).

Generated by scripts/update_plugin_lock.py — do not edit by hand. Only
these may be auto-installed by `-m` / `suggest --install`, and only at
the pinned commit.
"""

OFFICIAL_PLUGINS: list[dict] = [
    {
        'repo': 'attackmap-analyzer-python',
        'package': 'attackmap-analyzer-python',
        'version': '0.1.0',
        'git_sha': '1bcce0dd5d639cb83ada65cc3f5024bb5a1d9782',
        'entry_points': ['python'],
    },
    {
        'repo': 'attackmap-analyzer-rust',
        'package': 'attackmap-analyzer-rust',
        'version': '0.1.0',
        'git_sha': 'c2e02d2855e6102153140f2644504b1cc0a95fb8',
        'entry_points': ['rust'],
    },
    {
        'repo': 'attackmap-analyzer-go',
        'package': 'attackmap-analyzer-go',
        'version': '0.1.0',
        'git_sha': 'e92fc3de5c34485c4ea06032052ad0f6c21fd133',
        'entry_points': ['go'],
    },
    {
        'repo': 'attackmap-analyzer-java-spring',
        'package': 'attackmap-analyzer-java-spring',
        'version': '0.1.0',
        'git_sha': '98dec01669ca90216cea4559495ee310224fd8f3',
        'entry_points': ['java_spring'],
    },
    {
        'repo': 'attackmap-analyzer-dotnet',
        'package': 'attackmap-analyzer-dotnet',
        'version': '0.1.0',
        'git_sha': 'a1f00d05bc915940ed684f438c678e696f3de53d',
        'entry_points': ['dotnet'],
    },
    {
        'repo': 'attackmap-analyzer-terraform',
        'package': 'attackmap-analyzer-terraform',
        'version': '0.1.0',
        'git_sha': '736f2c22051ffca537785edebf941a2d5ddb2487',
        'entry_points': ['terraform'],
    },
    {
        'repo': 'attackmap-analyzer-c',
        'package': 'attackmap-analyzer-c',
        'version': '0.1.0',
        'git_sha': '1c2789ef62e57b713789f483b9409a5c64644795',
        'entry_points': ['c'],
    },
    {
        'repo': 'attackmap-analyzer-cpp',
        'package': 'attackmap-analyzer-cpp',
        'version': '0.1.0',
        'git_sha': '61fa5325696620665bf9ceab10ec7bed378888ec',
        'entry_points': ['cpp'],
    },
    {
        'repo': 'attackmap-analyzer-swift',
        'package': 'attackmap-analyzer-swift',
        'version': '0.1.0',
        'git_sha': 'bae13e58a49f46c15992197517cf9c036a75d83c',
        'entry_points': ['swift'],
    },
    {
        'repo': 'attackmap-analyzer-node-service',
        'package': 'attackmap-analyzer-node-service',
        'version': '0.2.0',
        'git_sha': '8573b4a8dcefda5518a771c1a84be93b2eb9be05',
        'entry_points': ['node_service'],
    },
    {
        'repo': 'attackmap-analyzer-atproto',
        'package': 'attackmap-analyzer-atproto',
        'version': '0.1.0',
        'git_sha': 'd2cb6ed6d5e69adf929a1fd7f66947830ecfd5fc',
        'entry_points': ['atproto'],
    },
    {
        'repo': 'attackmap-analyzer-php-web',
        'package': 'attackmap-analyzer-php-web',
        'version': '0.1.0',
        'git_sha': '69143bd994ec9111cffc2f78d4020bad611e68c7',
        'entry_points': ['php_web'],
    },
    {
        'repo': 'attackmap-analyzer-php-laminas',
        'package': 'attackmap-analyzer-php-laminas',
        'version': '0.1.0',
        'git_sha': '7eac668b6f64a1d3fc3fa731317cb253a98915ce',
        'entry_points': ['php_laminas'],
    },
    {
        'repo': 'attack-map-analyzer-omeka-s',
        'package': 'attackmap-analyzer-omeka-s',
        'version': '0.1.0',
        'git_sha': '6b9e478689a825dbcba655de4ff0bf63a3a3c544',
        'entry_points': ['omeka_s'],
    },
    {
        'repo': 'attackmap-analyzer-iac',
        'package': 'attackmap-analyzer-iac',
        'version': '0.1.0',
        'git_sha': '002efc484fc26ead1243aa34b610ccb2230147b0',
        'entry_points': ['iac'],
    },
]
