"""Bundled popular-package names for offline typosquat detection (#247).

Versioned, offline and deterministic: no network lookup ever happens. The
lists are curated from widely used packages (PyPI download rankings and the
most-depended-upon npm packages), and also carry near-twins of popular names
(`boto`/`boto3`, `scipy`/`scapy`) so a legitimate package isn't flagged as a
squat of its neighbour. Bump ``POPULAR_PACKAGES_VERSION`` when editing.

PyPI names are PEP 503-normalized (lowercase, runs of ``-_.`` → ``-``).
"""

from __future__ import annotations

POPULAR_PACKAGES_VERSION = "2026.10.1"

PYPI: frozenset[str] = frozenset((
    "accelerate", "adal", "aiobotocore", "aiohttp", "aiosignal", "alabaster",
    "alembic", "altair", "amqp", "angr", "annotated-types", "ansible", "ansible-core",
    "anthropic", "anyio", "apscheduler", "arcade", "argon2-cffi", "ariadne", "arrow",
    "asgiref", "astroid", "asttokens", "async-timeout", "asyncpg", "attrs", "authlib",
    "automat", "autopep8", "awscli", "azure-common", "azure-core", "azure-identity",
    "azure-storage-blob", "babel", "backoff", "bandit", "bcrypt", "beautifulsoup4",
    "bidict", "billiard", "binaryornot", "black", "bleach", "blinker", "bokeh", "boto",
    "boto3", "botocore", "build", "cachecontrol", "cachetools", "capstone",
    "cassandra-driver", "catboost", "cattrs", "celery", "certifi", "cffi", "cfgv",
    "channels", "chardet", "charset-normalizer", "click", "cloudpickle", "cmake",
    "colorama", "colorlog", "comm", "comtypes", "confluent-kafka", "constantly",
    "contourpy", "cookiecutter", "coverage", "croniter", "cryptography", "cssselect",
    "cx-freeze", "cycler", "cython", "cytoolz", "daphne", "dash", "dask",
    "dataclasses-json", "datadog", "datasets", "ddtrace", "debugpy", "decorator",
    "deepdiff", "defusedxml", "dill", "diskcache", "distlib", "distributed", "django",
    "django-cors-headers", "djangorestframework", "dnspython", "docker", "docutils",
    "duckdb", "dynaconf", "ecdsa", "elasticsearch", "email-validator", "emoji",
    "environs", "et-xmlfile", "eventlet", "exceptiongroup", "execnet", "executing",
    "fabric", "factory-boy", "faker", "fastapi", "feedparser", "filelock", "findspark",
    "fiona", "flake8", "flask", "flask-cors", "flask-jwt-extended", "flask-login",
    "flask-migrate", "flask-restful", "flask-sqlalchemy", "flask-wtf", "flit-core",
    "fonttools", "freezegun", "frida", "frida-tools", "frozenlist", "fsspec", "ftfy",
    "gensim", "geopandas", "gevent", "gnupg", "google-api-core",
    "google-api-python-client", "google-auth", "google-auth-httplib2",
    "google-auth-oauthlib", "google-cloud-core", "google-cloud-storage",
    "google-crc32c", "google-resumable-media", "googleapis-common-protos", "gradio",
    "graphene", "graphql-core", "greenlet", "grpcio", "grpcio-status", "gunicorn",
    "h11", "h5py", "hatchling", "html5lib", "httpcore", "httplib2", "httptools",
    "httpx", "huggingface-hub", "humanize", "hyperlink", "hypothesis", "identify",
    "idna", "imageio", "imagesize", "impacket", "importlib-metadata", "incremental",
    "iniconfig", "invoke", "ipaddress", "ipykernel", "ipython", "ipywidgets",
    "isodate", "isort", "itemadapter", "itsdangerous", "jaraco-classes", "jedi",
    "jeepney", "jinja2", "jinja2-time", "jmespath", "joblib", "jsonpatch",
    "jsonpath-ng", "jsonpointer", "jsonschema", "jsonschema-specifications", "jupyter",
    "jupyter-client", "jupyter-core", "jupyterlab", "jupyterlab-server", "jwcrypto",
    "kafka-python", "keras", "keyring", "keystone-engine", "kivy", "kiwisolver",
    "kombu", "kubernetes", "langchain", "langchain-community", "langchain-core",
    "langdetect", "lief", "lightgbm", "llvmlite", "locket", "loguru", "lxml", "mako",
    "markdown", "markdown-it-py", "markupsafe", "marshmallow", "matplotlib",
    "matplotlib-inline", "mccabe", "mdurl", "meson", "mistune", "mkdocs",
    "mkdocs-material", "mock", "more-itertools", "moto", "motor", "mpmath", "msal",
    "msal-extensions", "msgpack", "msrest", "msrestazure", "multidict", "mypy",
    "mypy-extensions", "mysqlclient", "nbclient", "nbconvert", "nbformat",
    "nest-asyncio", "netaddr", "netcdf4", "netifaces", "networkx", "ninja", "nltk",
    "nmap", "nodeenv", "nose", "nose2", "notebook", "nox", "numba", "numpy",
    "oauth2client", "oauthlib", "openai", "opencv-python", "opencv-python-headless",
    "openpyxl", "opentelemetry-api", "opentelemetry-sdk", "orjson", "packaging",
    "pandas", "pandocfilters", "paramiko", "parsel", "parso", "partd", "passlib",
    "patsy", "pdm", "peewee", "pefile", "pendulum", "pexpect", "phonenumbers", "pika",
    "pillow", "pip", "pkginfo", "platformdirs", "playwright", "plotly", "pluggy",
    "poetry", "poetry-core", "polars", "pony", "pre-commit", "prettytable",
    "prometheus-client", "prompt-toolkit", "protobuf", "psutil", "psycopg", "psycopg2",
    "psycopg2-binary", "ptyprocess", "pure-eval", "pwntools", "py2exe", "py4j",
    "pyarrow", "pyasn1", "pyasn1-modules", "pybind11", "pycodestyle", "pycountry",
    "pycparser", "pycryptodome", "pycryptodomex", "pydantic", "pydantic-core",
    "pydantic-settings", "pyelftools", "pyflakes", "pygame", "pyglet", "pygments",
    "pyhamcrest", "pyinstaller", "pyjwt", "pylint", "pymdown-extensions", "pymongo",
    "pymysql", "pynacl", "pyobjc", "pyopengl", "pyopenssl", "pyotp", "pyparsing",
    "pyppeteer", "pyproj", "pyproject-hooks", "pyqt5", "pyqt6", "pyquery",
    "pyrsistent", "pyside6", "pysnmp", "pyspark", "pytest", "pytest-asyncio",
    "pytest-cov", "pytest-mock", "pytest-timeout", "pytest-xdist", "python-dateutil",
    "python-dotenv", "python-engineio", "python-gnupg", "python-jose",
    "python-multipart", "python-nmap", "python-slugify", "python-socketio", "pytz",
    "pyvmomi", "pywin32", "pywin32-ctypes", "pyyaml", "pyzmq", "qrcode", "r2pipe",
    "readme-renderer", "redis", "redis-py-cluster", "referencing", "regex", "requests",
    "requests-mock", "requests-oauthlib", "responses", "retrying", "rich", "ropgadget",
    "rpds-py", "rsa", "ruff", "s3fs", "s3transfer", "safetensors", "salt", "scapy",
    "schedule", "scikit-build", "scikit-image", "scikit-learn", "scipy", "scrapy",
    "seaborn", "secretstorage", "selenium", "sentencepiece", "sentry-sdk",
    "service-identity", "setuptools", "setuptools-scm", "shapely", "shellingham",
    "shodan", "simplejson", "six", "sniffio", "snowballstemmer",
    "snowflake-connector-python", "sortedcontainers", "soupsieve", "spacy", "sphinx",
    "sphinx-rtd-theme", "sqlalchemy", "sqlalchemy-utils", "sqlparse", "stack-data",
    "starlette", "statsmodels", "strawberry-graphql", "streamlit", "structlog",
    "sympy", "tables", "tabulate", "tblib", "tenacity", "tensorboard", "tensorflow",
    "termcolor", "text-unidecode", "threadpoolctl", "tifffile", "tiktoken", "tinycss2",
    "tokenizers", "toml", "tomli", "tomlkit", "toolz", "torch", "torchaudio",
    "torchvision", "tornado", "tortoise-orm", "tox", "tqdm", "traitlets",
    "transformers", "twine", "twisted", "typer", "typing-extensions", "tzdata",
    "ujson", "unicorn", "unidecode", "uritemplate", "urllib3", "uvicorn", "uvloop",
    "vine", "virtualenv", "w3lib", "watchdog", "watchfiles", "wcwidth", "webencodings",
    "websocket-client", "websockets", "werkzeug", "wheel", "wrapt", "wtforms",
    "wxpython", "xarray", "xgboost", "xmltodict", "yapf", "yara-python", "yarl",
    "z3-solver", "zict", "zipp", "zope-interface",
))

NPM: frozenset[str] = frozenset((
    "@apollo/client", "@aws-sdk/client-s3", "@babel/core", "@babel/generator",
    "@babel/parser", "@babel/preset-env", "@babel/preset-react",
    "@babel/preset-typescript", "@babel/runtime", "@babel/traverse", "@babel/types",
    "@emotion/react", "@emotion/styled", "@material-ui/core", "@mui/material",
    "@nestjs/common", "@nestjs/core", "@prisma/client", "@reduxjs/toolkit",
    "@tanstack/react-query", "@types/express", "@types/jest", "@types/lodash",
    "@types/node", "@types/react", "@types/react-dom",
    "@typescript-eslint/eslint-plugin", "@typescript-eslint/parser", "accepts",
    "adm-zip", "ajv", "ajv-keywords", "amqplib", "angular", "ansi-regex",
    "ansi-styles", "antd", "anymatch", "apollo-server", "archiver", "array-flatten",
    "async", "asynckit", "autoprefixer", "aws-sdk", "axios", "babel-core",
    "babel-loader", "balanced-match", "base64-js", "bcrypt", "bcryptjs",
    "better-sqlite3", "big.js", "binary-extensions", "bindings", "bl", "bluebird",
    "body-parser", "bootstrap", "boxen", "brace-expansion", "braces", "browserify",
    "browserslist", "buffer", "buffer-from", "bull", "bullmq", "bunyan", "busboy",
    "bytes", "call-bind", "callsites", "camelcase", "caniuse-lite", "canvas", "chai",
    "chalk", "chart.js", "cheerio", "chokidar", "chownr", "class-transformer",
    "class-validator", "classnames", "clean-css", "cli-spinners", "clipboardy",
    "cliui", "clone", "color-convert", "color-name", "colors", "combined-stream",
    "commander", "compression", "concat-map", "concurrently", "configstore",
    "content-disposition", "content-type", "cookie", "cookie-parser",
    "copy-webpack-plugin", "core-js", "core-util-is", "cors", "cosmiconfig", "cpy-cli",
    "cross-env", "cross-fetch", "cross-spawn", "crypto-js", "css-loader", "cssnano",
    "csv-parse", "d3", "date-fns", "dayjs", "debug", "decamelize", "deep-equal",
    "deep-extend", "deepmerge", "define-properties", "delayed-stream", "depd",
    "destroy", "dotenv", "duplexify", "ee-first", "ejs", "electron-to-chromium",
    "emojis-list", "encodeurl", "end-of-stream", "engine.io", "enhanced-resolve",
    "enquirer", "es-abstract", "esbuild", "escape-html", "escape-string-regexp",
    "eslint", "eslint-config-airbnb", "eslint-config-prettier", "eslint-plugin-import",
    "eslint-plugin-jsx-a11y", "eslint-plugin-prettier", "eslint-plugin-react",
    "eslint-plugin-react-hooks", "etag", "eventemitter3", "events", "exceljs", "execa",
    "express", "express-session", "fast-deep-equal", "fast-json-stable-stringify",
    "fast-xml-parser", "fastify", "figures", "file-loader", "fill-range",
    "finalhandler", "find-up", "firebase", "firebase-admin",
    "fork-ts-checker-webpack-plugin", "form-data", "formidable", "formik", "forwarded",
    "fresh", "fs-extra", "fs-minipass", "fsevents", "function-bind", "get-caller-file",
    "get-intrinsic", "get-stream", "glob", "glob-parent", "googleapis", "got",
    "graceful-fs", "graphql", "graphql-tag", "grunt", "gulp", "handlebars", "hapi",
    "has", "has-flag", "hasown", "helmet", "highlight.js", "history",
    "html-webpack-plugin", "http-errors", "http-proxy", "http-proxy-middleware",
    "human-signals", "husky", "iconv-lite", "ieee754", "immer", "immutable",
    "import-fresh", "inflight", "inherits", "ini", "inquirer", "ioredis", "ipaddr.js",
    "is-core-module", "is-docker", "is-extglob", "is-glob", "is-number", "is-stream",
    "is-wsl", "isarray", "isexe", "isomorphic-fetch", "jasmine", "jest", "jimp", "joi",
    "jquery", "js-tokens", "js-yaml", "jsdom", "json-schema-traverse",
    "json-stable-stringify", "json5", "jsonfile", "jsonwebtoken", "jszip", "kafkajs",
    "karma", "kleur", "knex", "koa", "koa-router", "latest-version", "leaflet", "less",
    "lint-staged", "listr2", "loader-utils", "locate-path", "lodash",
    "lodash.debounce", "lodash.get", "lodash.isequal", "lodash.merge", "log-symbols",
    "log4js", "loose-envify", "lru-cache", "luxon", "mapbox-gl", "markdown-it",
    "marked", "media-typer", "memory-fs", "meow", "merge-descriptors", "merge-stream",
    "methods", "micromatch", "mime", "mime-db", "mime-types", "mimic-fn",
    "mini-css-extract-plugin", "minimatch", "minimist", "minipass", "mitt", "mkdirp",
    "mobx", "mocha", "moment", "mongodb", "mongoose", "morgan", "ms", "multer",
    "mustache", "mysql", "mysql2", "nan", "nanoid", "needle", "negotiator",
    "neo-async", "next", "node-addon-api", "node-fetch", "node-gyp", "node-releases",
    "nodemailer", "nodemon", "normalize-path", "npm-run-all", "npm-run-path",
    "numeral", "nunjucks", "nuxt", "object-assign", "object-keys", "on-finished",
    "once", "onetime", "open", "opn", "ora", "p-limit", "p-locate", "p-try",
    "package-json", "papaparse", "parcel", "parent-module", "passport", "passport-jwt",
    "passport-local", "path-exists", "path-is-absolute", "path-key", "path-parse",
    "path-to-regexp", "pdfkit", "pg", "pg-promise", "picocolors", "picomatch", "pino",
    "pkg-dir", "playwright", "postcss", "postcss-loader", "prebuild-install",
    "prettier", "prisma", "process-nextick-args", "prompts", "prop-types",
    "proxy-addr", "psl", "pug", "pump", "punycode", "puppeteer", "qs", "query-string",
    "querystring", "range-parser", "raw-body", "rc", "react", "react-bootstrap",
    "react-dom", "react-hook-form", "react-query", "react-redux", "react-router",
    "react-router-dom", "readable-stream", "readdirp", "recoil", "redis", "redux",
    "redux-saga", "redux-thunk", "reflect-metadata", "regenerator-runtime",
    "registry-url", "request", "require-directory", "resolve", "resolve-from",
    "restify", "rimraf", "rollup", "rxjs", "rxjs-compat", "safe-buffer", "sass",
    "sass-loader", "schema-utils", "selenium-webdriver", "semver", "send", "sequelize",
    "serve-favicon", "serve-static", "setprototypeof", "sharp", "shebang-command",
    "shebang-regex", "shelljs", "showdown", "signal-exit", "sinon", "socket.io",
    "socket.io-client", "source-map", "source-map-support", "sqlite3", "statuses",
    "stream-shift", "string-width", "string_decoder", "strip-ansi",
    "strip-final-newline", "strip-json-comments", "stripe", "style-loader",
    "styled-components", "stylus", "superagent", "supports-color", "svelte", "swr",
    "tailwindcss", "tapable", "tar", "tar-stream", "terser", "terser-webpack-plugin",
    "three", "through2", "to-regex-range", "toidentifier", "tough-cookie", "ts-loader",
    "ts-node", "tslib", "twilio", "type-is", "typeorm", "typescript", "uglify-js",
    "underscore", "universalify", "unpipe", "unzipper", "update-browserslist-db",
    "update-notifier", "uri-js", "url-loader", "url-parse", "util-deprecate",
    "utils-merge", "uuid", "validator", "vary", "vite", "vue", "watchpack", "webpack",
    "webpack-cli", "webpack-dev-server", "whatwg-fetch", "which", "winston",
    "wrap-ansi", "wrappy", "ws", "xdg-basedir", "xlsx", "xml2js", "y18n", "yallist",
    "yaml", "yargs", "yargs-parser", "yup", "zod", "zone.js", "zustand",
))

BY_ECOSYSTEM: dict[str, frozenset[str]] = {"pypi": PYPI, "npm": NPM}
