#!/usr/bin/env python3
"""Regenerate src/attackmap/plugins_lock.py and the `[all]` extra pins (#237).

Resolves each official analyzer repo's current `main` to an immutable commit
SHA and reads the package name/version from its pyproject at that commit.
Run at release time:  python scripts/update_plugin_lock.py
"""

from __future__ import annotations

import re
import subprocess
import tomllib
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ORG = "mlaify"
REPOS = [
    "attackmap-analyzer-python", "attackmap-analyzer-rust", "attackmap-analyzer-go",
    "attackmap-analyzer-java-spring", "attackmap-analyzer-dotnet", "attackmap-analyzer-terraform",
    "attackmap-analyzer-c", "attackmap-analyzer-cpp", "attackmap-analyzer-swift",
    "attackmap-analyzer-node-service", "attackmap-analyzer-atproto", "attackmap-analyzer-php-web",
    "attackmap-analyzer-php-laminas", "attack-map-analyzer-omeka-s", "attackmap-analyzer-iac",
]


def _head_sha(repo: str) -> str:
    out = subprocess.run(
        ["git", "ls-remote", f"https://github.com/{ORG}/{repo}.git", "refs/heads/main"],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    return out[0]


def _pyproject(repo: str, sha: str) -> dict:
    url = f"https://raw.githubusercontent.com/{ORG}/{repo}/{sha}/pyproject.toml"
    with urllib.request.urlopen(url, timeout=30) as resp:  # noqa: S310 - fixed https URL
        return tomllib.loads(resp.read().decode("utf-8"))


def main() -> None:
    entries = []
    for repo in REPOS:
        sha = _head_sha(repo)
        project = _pyproject(repo, sha)["project"]
        eps = project.get("entry-points", {}).get("attackmap.analyzers", {})
        entries.append({
            "repo": repo, "package": project["name"], "version": project["version"],
            "git_sha": sha, "entry_points": sorted(eps),
        })
    rows = []
    for e in entries:
        fields = "".join(f"        {k!r}: {v!r},\n" for k, v in e.items())
        rows.append(f"    {{\n{fields}    }},\n")
    body = "[\n" + "".join(rows) + "]"
    (ROOT / "src/attackmap/plugins_lock.py").write_text(
        '"""Official analyzer plugins, pinned to immutable commits (#237).\n\n'
        "Generated by scripts/update_plugin_lock.py — do not edit by hand. Only\n"
        "these may be auto-installed by `-m` / `suggest --install`, and only at\n"
        'the pinned commit.\n"""\n\n'
        f"OFFICIAL_PLUGINS: list[dict] = {body}\n",
        encoding="utf-8",
    )
    pyproject = ROOT / "pyproject.toml"
    text = pyproject.read_text(encoding="utf-8")
    for e in entries:
        pattern = re.compile(rf'"{re.escape(e["package"])} @ git\+https://github\.com/{ORG}/{re.escape(e["repo"])}\.git(?:@[0-9a-f]+)?"')
        text, n = pattern.subn(f'"{e["package"]} @ git+https://github.com/{ORG}/{e["repo"]}.git@{e["git_sha"]}"', text)
        if n != 1:
            raise SystemExit(f"[all] extra entry for {e['repo']} not found exactly once in pyproject.toml")
    pyproject.write_text(text, encoding="utf-8")
    print(f"pinned {len(entries)} plugins")


if __name__ == "__main__":
    main()
